name: Testing
on:
  push:
    branches:
    - main
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app && /usr/bin/xcodebuild -version
      #- name: install simulator
      #  run: xcversion simulators --install='iOS 15.0'
      - name: Prepare iOS 15.0 simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_13.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 15.0.simruntime
          xcrun simctl list runtimes
          xcrun simctl create iPhone_12 "iPhone 12" "com.apple.CoreSimulator.SimRuntime.iOS-15-0"
          xcrun simctl list devices 15.0
          
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Install pods to prepare workspace
        run: pod install
    
      - name: Show Build Settings
        run: xcodebuild -workspace DemoToptalCI.xcworkspace -scheme DemoToptalCI -showBuildSettings
        
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh

#      - name: clean and build
#        run: xcodebuild clean build -workspace DemoToptalCI.xcworkspace -scheme DemoToptalCI -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12' -showBuildTimingSummary
        
#      - name: build and test
#        run: xcodebuild clean build test -workspace DemoToptalCI.xcworkspace -scheme "DemoToptalCI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.0,name=iPhone 12" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO


