name: Testing
on:
  push:
    branches:
    - main
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app
#      - name: Testing Swift package
#        run: exec ./.github/scripts/test_swift_package.sh
      - name: Testing iOS app
        run: exec .github/scripts/test_app.sh
