name: Testing
on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Testing iOS app
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app && /usr/bin/xcodebuild -version
          
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Install pods to prepare workspace
        run: pod install
 
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh

